#!/usr/bin/env bash

set -euo pipefail

mise run node-dupcheck
mise run test

if [ -f .env ]; then
  set -a
  . ./.env
  set +a
fi

if [ -n "${RUN_INTEGRATION_TESTS_AT_PRE_PUSH:-}" ]; then
  npm run test:integration
fi
